services:
  redis:
    image: redis:alpine
    container_name: redis-rate-limiter

  app:
    build: .
    container_name: rate-limiter-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis-rate-limiter:6379
    volumes:
      - ./app.env:/app/app.env
    command: ["/app/main"]
